import type { SkillNode } from "../types";
import { nanoid } from "nanoid";

const makeNode = (config: Omit<SkillNode, "id">): SkillNode => ({
  id: nanoid(),
  ...config,
});

export const skillTree: SkillNode[] = [
  makeNode({
    key: "glass-cannon",
    path: "Offense",
    maxRank: 5,
    description: "Increase damage but reduce defences.",
    requires: [],
    perRank: { firePower: 6, icePower: 6, voltPower: 6, hp: -8 },
    synergies: ["Elemental Overload"],
  }),
  makeNode({
    key: "rapid-servo",
    path: "Offense",
    maxRank: 3,
    description: "Increase fire rate and reload speed.",
    requires: [{ nodeKey: "glass-cannon", rank: 2 }],
    perRank: { fireRate: 0.15, reload: -0.08 },
  }),
  makeNode({
    key: "piercing-rounds",
    path: "Offense",
    maxRank: 4,
    description: "Projectiles pierce additional targets.",
    requires: [{ nodeKey: "rapid-servo", rank: 1 }],
    perRank: { notes: "+1 pierce", critDamage: 4 },
  }),
  makeNode({
    key: "elemental-overload",
    path: "Offense",
    maxRank: 3,
    description: "Elemental power scales core status effects.",
    requires: [{ nodeKey: "piercing-rounds", rank: 2 }],
    perRank: { firePower: 10, icePower: 10, voltPower: 10 },
    gateUnlockKey: "Molten Core",
  }),
  makeNode({
    key: "perfect-reload",
    path: "Offense",
    maxRank: 2,
    description: "Perfect reload windows grant bonus crit.",
    requires: [{ nodeKey: "rapid-servo", rank: 2 }],
    perRank: { critChance: 6, reload: -0.12 },
  }),
  makeNode({
    key: "chain-spark",
    path: "Offense",
    maxRank: 4,
    description: "Shock damage arcs to nearby foes.",
    requires: [{ nodeKey: "elemental-overload", rank: 1 }],
    perRank: { voltPower: 8, notes: "+1 chain" },
    synergies: ["Storm Warden"],
  }),
  makeNode({
    key: "cryo-trap",
    path: "Control",
    maxRank: 4,
    description: "Deploy cryo traps that chill enemies.",
    requires: [],
    perRank: { icePower: 5, cdr: 0.03 },
  }),
  makeNode({
    key: "vortex-grenade",
    path: "Control",
    maxRank: 3,
    description: "Creates a singularity pulling enemies.",
    requires: [{ nodeKey: "cryo-trap", rank: 2 }],
    perRank: { voltPower: 4, notes: "+0.3 pull strength" },
  }),
  makeNode({
    key: "graviton-bullets",
    path: "Control",
    maxRank: 2,
    description: "Bullets slow enemies hit.",
    requires: [{ nodeKey: "vortex-grenade", rank: 1 }],
    perRank: { icePower: 6, notes: "+5% slow" },
  }),
  makeNode({
    key: "temporal-dilation",
    path: "Control",
    maxRank: 3,
    description: "Dodge triggers brief bullet-time.",
    requires: [{ nodeKey: "graviton-bullets", rank: 2 }],
    perRank: { cdr: 0.05, dashCharges: 0.25 },
    gateUnlockKey: "Temporal Key",
  }),
  makeNode({
    key: "kinetic-plating",
    path: "Survivability",
    maxRank: 5,
    description: "Increase shields based on movement.",
    requires: [],
    perRank: { shield: 12, moveSpeed: 0.05 },
  }),
  makeNode({
    key: "second-wind",
    path: "Survivability",
    maxRank: 1,
    description: "Revive with partial health once per run.",
    requires: [{ nodeKey: "kinetic-plating", rank: 3 }],
    perRank: { hp: 50, notes: "On downed revive" },
  }),
  makeNode({
    key: "aegis-dash",
    path: "Survivability",
    maxRank: 3,
    description: "Dash grants temporary barrier.",
    requires: [{ nodeKey: "kinetic-plating", rank: 2 }],
    perRank: { dashCharges: 0.2, shield: 8 },
  }),
  makeNode({
    key: "leeching-shots",
    path: "Survivability",
    maxRank: 4,
    description: "Shots heal a portion of damage dealt.",
    requires: [
      { nodeKey: "aegis-dash", rank: 2 },
      { nodeKey: "glass-cannon", rank: 1 },
    ],
    perRank: { notes: "+1% life steal", hp: 6 },
    gateUnlockKey: "Royal Jelly",
  }),
  makeNode({
    key: "scavengers-luck",
    path: "Utility",
    maxRank: 5,
    description: "Increased loot quantity and rarity chance.",
    requires: [],
    perRank: { notes: "+2% rarity", voltPower: 2 },
  }),
  makeNode({
    key: "field-engineer",
    path: "Utility",
    maxRank: 3,
    description: "Deploy an automated turret.",
    requires: [{ nodeKey: "scavengers-luck", rank: 2 }],
    perRank: { cdr: 0.04, voltPower: 4 },
  }),
  makeNode({
    key: "holo-decoy",
    path: "Utility",
    maxRank: 2,
    description: "Deploy decoys that draw fire.",
    requires: [{ nodeKey: "field-engineer", rank: 1 }],
    perRank: { moveSpeed: 0.05, notes: "+1 decoy" },
  }),
  makeNode({
    key: "pack-mule",
    path: "Utility",
    maxRank: 3,
    description: "Increase inventory size and pickup radius.",
    requires: [{ nodeKey: "scavengers-luck", rank: 1 }],
    perRank: { notes: "+2 bag slots", moveSpeed: 0.03 },
  }),
  makeNode({
    key: "mobility-mastery",
    path: "Utility",
    maxRank: 4,
    description: "Improve sprint and dodge performance.",
    requires: [{ nodeKey: "pack-mule", rank: 2 }],
    perRank: { dashCharges: 0.3, stamina: 8 },
  }),
  makeNode({
    key: "burning-resonance",
    path: "Offense",
    maxRank: 3,
    description: "Burn stacks deal increased damage.",
    requires: [{ nodeKey: "elemental-overload", rank: 2 }],
    perRank: { firePower: 12 },
  }),
  makeNode({
    key: "chill-breaker",
    path: "Control",
    maxRank: 3,
    description: "Shattering chilled enemies causes AoE damage.",
    requires: [{ nodeKey: "vortex-grenade", rank: 2 }],
    perRank: { icePower: 8 },
    gateUnlockKey: "Glacier Heart",
  }),
  makeNode({
    key: "storm-channel",
    path: "Offense",
    maxRank: 3,
    description: "Converts crits into shock novas.",
    requires: [{ nodeKey: "chain-spark", rank: 2 }],
    perRank: { voltPower: 12, critChance: 2 },
    gateUnlockKey: "Capacitor Spine",
  }),
  makeNode({
    key: "void-synthesis",
    path: "Utility",
    maxRank: 2,
    description: "Ultimate unlock providing run-altering power.",
    requires: [
      { nodeKey: "mobility-mastery", rank: 4 },
      { nodeKey: "storm-channel", rank: 1 },
    ],
    perRank: { notes: "Unlock ultimate" },
    gateUnlockKey: "Void Feather",
  }),
  makeNode({
    key: "resonant-barrier",
    path: "Survivability",
    maxRank: 3,
    description: "Barrier pulses apply shock to attackers.",
    requires: [{ nodeKey: "leeching-shots", rank: 2 }],
    perRank: { shield: 10, voltPower: 6 },
  }),
];

export default skillTree;
